# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres-14
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=}${DB_URL}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USERNAME=${DB_USER}
    env_file:
      - .env
      

  vk-api:
    image: openjdk:17
    container_name: vk-api
    ports:
      - "9500:9500"
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./target/vkapi-0.0.1-SNAPSHOT.jar:/opt/app.jar
      - ./.env:/.env
    command: java -jar -Ddb.url=jdbc:postgresql://postgres:5432/postgres /opt/app.jar
    env_file:
      - .env